# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-10 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[(b'male', b'male'), (b'female', b'female')], default=b'male', max_length=32),
        ),
    ]
